# Generated by Django 5.1.2 on 2024-10-25 23:38

import django.db.models.deletion
import homepage.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(default='#000000', max_length=7, validators=[homepage.validators.validate_hex_color])),
                ('background', models.CharField(default='#FFFFFF', max_length=7, validators=[homepage.validators.validate_hex_color])),
            ],
        ),
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=24)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/shortcuts/')),
                ('new_tab', models.BooleanField(default=False)),
                ('color', models.CharField(default='#000000', max_length=7, validators=[homepage.validators.validate_hex_color])),
                ('background', models.CharField(default='#FFFFFF', max_length=7, validators=[homepage.validators.validate_hex_color])),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=42)),
                ('description', models.CharField(max_length=128)),
                ('article', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/news/')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.articlecategory')),
            ],
        ),
    ]
