# Generated by Django 5.1.2 on 2024-10-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shortcuts/'),
        ),
    ]
